### ISSUE TITLE
Introduction and Attribution sections of CoC carry redundant info

### ISSUE THREAD

**Issue by sreekaransrinath** [OurTechCommunity/website#11]
Both sections have essentially the same info. 

![image](https://user-images.githubusercontent.com/50989977/195739050-4da603e7-994b-4a8a-9152-a840d0150bd1.png)

![image](https://user-images.githubusercontent.com/50989977/195739037-ac61ee84-cc6b-4721-8050-2923051d3ccc.png)

Motion to strike the Introduction and start with the Pledge.

**Comment by tusharnankani** [comment]
Alright, that makes sense. Let's start with the pledge.

Let's make the changes in PR #12 itself.

**Comment by sreekaransrinath** [comment]
Closing since #12 fixes this
