### ISSUE TITLE
Add team member query parameter support on the team page

### ISSUE THREAD

**Issue by HarshKapadia2** [OurTechCommunity/website#5]
- Add support to show individual team member info.
- URL pattern: `https://ourtech.community/team/?[kartik | harsh | darshan | dheeraj | sreekaran]`

**Comment by tusharnankani** [comment]
Why do we need this again?

**Comment by HarshKapadia2** [comment]
I don't clearly remember, but it was suggested by @KartikSoneji.
I think it was so that we're able to share profiles easily, but I can't think of a reason why we would need that right now.
Should we close this issue @KartikSoneji?

**Comment by KartikSoneji** [comment]
I think that was when we had Sreekaran's position as Chief Meme Officer, and clicking on a profile expanded it or something.
Since the page is static now I don't think we need it.

**Comment by tusharnankani** [comment]
Oof. Please close this if that's the case.
