### ISSUE TITLE
Fix the mobile view of the admin page

### ISSUE THREAD

**Issue by dheerajdlalwani** [OurTechCommunity/website#6]
![image](https://user-images.githubusercontent.com/52416311/146398495-6e2aee35-b0b4-4e97-a189-4b8e0baec78a.png)

**Comment by tusharnankani** [comment]
Hi @dheerajdlalwani 
Can you send in your device, browser details and dimensions?

![image](https://user-images.githubusercontent.com/61280281/146825911-81fff307-e7fb-446d-8c29-7e85cc5b628a.png)

Works alright for me^

Also, if I am not wrong this issue will go in [OurTechCommunity/catchup](https://github.com/OurTechCommunity/catchup/issues).

**Comment by dheerajdlalwani** [comment]
It is a Samsung Galaxy J6 
5.6 inches screen 
Chrome browser version: 96.0.4664.104
It works fine when seen through dev tools. 
But open on actual device and check.

**Comment by tusharnankani** [comment]
Thank you, Dheeraj!

Yes, a margin will definitely look better.
 
<img src="https://user-images.githubusercontent.com/61280281/146985480-e79d42ec-1166-4ccd-bc33-790c5cfc31c0.jpg" width="50%" />

**Comment by tusharnankani** [comment]
Moved this issue to [catchup](https://github.com/OurTechCommunity/catchup): [Issue #11](https://github.com/OurTechCommunity/catchup/issues/11#issue-1086886323)

**Comment by HarshKapadia2** [comment]
Thank you so much, @tusharnankani! Appreciated!
