### ISSUE TITLE
Add Recurse's Social Rules terms to OTC's CoC

### ISSUE THREAD

**Issue by HarshKapadia2** [OurTechCommunity/website#7]
[Recurse's Social Rules](https://www.recurse.com/social-rules) are important things everyone should be aware of and follow, so add the four rules to the 'Introduction' section of the Code of Conduct (CoC) page and add a link to the Social Rules page as well, both in the 'Introduction' and the 'Attribution' sections.

Credits: @tusharnankani

**Comment by tusharnankani** [comment]
via: https://kentcdodds.com/conduct

**Comment by sreekaransrinath** [comment]
Any reason this is still pending? @HarshKapadia2 I see a lot of other potential fixes in the CoC; I'll go ahead and submit a couple of PRs.
