### ISSUE TITLE
bug: breaking buttons/text when responsive

### ISSUE THREAD

**Issue by tusharnankani** [OurTechCommunity/website#8]
753.x X 600px onwards
![image](https://user-images.githubusercontent.com/61280281/172328634-adc84554-2396-4619-a372-b30064740038.png)

till 753.x X 1032px
![image](https://user-images.githubusercontent.com/61280281/172328988-04309783-071e-40a3-9013-70cf36f4e16e.png)

**Comment by HarshKapadia2** [comment]
Fixed. Thank you @tusharnankani!
